
services:
  app:
    build: .  # Define que o serviço será construído a partir do Dockerfile no diretório atual.
    ports:
      - "3003:3002"  # Mapeia a porta 3002 do host para a porta 3002 do contêiner.
    volumes:
      - .:/usr/src/app  # Monta o diretório atual no host para o caminho /usr/src/app no contêiner.
    environment:
      - NODE_ENV=${NODE_ENV}  # Usa a variável NODE_ENV do arquivo .env
      - DB_HOST=${DB_HOST}      # Usa a variável DB_HOST do arquivo .env
      - DB_USER=${DB_USER}      # Usa a variável DB_USER do arquivo .env
      - DB_PASSWORD=${DB_PASSWORD}  # Usa a variável DB_PASSWORD do arquivo .env
    deploy:
      resources:
        limits:
          memory: 512M  # Limita o uso de memória do contêiner a 512 MB (ajustável conforme necessário).
